config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_for :teachers, controllers: {
        sessions: 'teachers/sessions'
      }
  devise_for :managers, controllers: {
      sessions: 'managers/sessions'
    }
  root :to => "home#index"

  get "select_courses", to: "home#select_courses", as: :select_courses_home
  get "courses/:number", to: "courses#show", as: :show_courses
  get "courses/:number/after_class", to: "courses#after_class", as: :after_class_courses
  resources :errors, only: :index
  #限定子课程编号为数字
  constraints(number: /\d+/) do
    get "sub_courses/:number", to: "sub_courses#show", as: :show_sub_courses
  end
  get "courses/:number/exams/new", to: "exams#new", as: :new_courses_exams

  post "sub_courses/comment_create_list"
  get "sub_courses/comment_create_list"
  post "sub_courses/reply_comment_list"
  get "sub_courses/comment_praise"
  post "sub_courses/collect_or_praise"
  
  #当子课程为pdf等格式文件时下载链接
  get "/sub_courses/:number/download", to: "sub_courses#download", as: :download_sub_course

  get "/learning_center", to: "courses#learning_center", as: :courses_learning_center
  resources :courses, only: [:index] do
  	resources :sub_courses, only: [:show]
    collection do
      post :course_collect
      post :course_praise
    end
  end

  resources :sub_courses, only: [:new, :create, :edit, :update, :destroy]

  #精品课程申报
  resources :apply_courses, only: [:index]

  #讨论中心
  resources :discusses, except: [:edit, :update, :destroy] do 
    collection do
      post :reply_topic
      get :sorts
      get :learns
      get :innovations
    end
  end

  # 测试中心
  resources :papers do
    member do
      get :questions
      patch :import
      get :students
    end

    resources :user_papers do
      collection do
        get :detail
        delete :destroy_grade
        get :export_grade
      end
    end
    resources :answers
  end

  #限定教师编号为数字形式
  constraints(number: /\d+/) do
    get "teachers/:number", to: "teachers#show", as: :show_teachers
  end

  resources :teachers, only: [:index, :update] do
    collection do
      get :my_courses
      get :my_grades
      get :my_info
      get :my_account
      get :upload_course_ware
      get :discuss_center
      get :my_questions
      get :my_answers
      get :my_score
      get :select_grade
      get :select_exam
      get :select_course
      get :show_score
      get :show_grade_score
      post :upload_attachment
      get :import_question
      post :import
      get :export
    end
    member do
      patch :update_password
      get :get_sub_course
      get :grade_students
    end
  end

  resources :exams, only: [:new, :create, :show, :index]  do 
    collection do
      get :test_new
      get :show_test
    end
  end

  resources :user, only: [:show, :update] do
    collection do
      post :get_specialties
      post :get_grades
      get :show
      get :my_courses
      get :my_exams
      get :score_search
      get :my_collect
      get :my_questions
      get :my_answers
      get :discuss_center

      post :update_password
    end
  end

  namespace :admin do
    root "home#index"
    resources :managers
    resources :specialties
    resources :questions, only: [] do
      collection do
         post :import
      end
    end
    resources :grades
    resources :courses do
      member do
        post :delete, :delete, :restore
        patch :delete, :delete, :restore
      end
      resources :sub_courses do
        member do
          patch :higher, :lower, :delete, :restore
          post :lower, :higher, :delete, :restore
        end
        resources :questions, only: [:index, :destroy]
      end
    end

    resources :teachers do
      collection do
        post :import
      end
    end

    resources :academies

    resources :categories

    resources :users do
      collection do
        post :import
      end
    end
  end

end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id                     :integer          not null, primary key
#  phone                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  username               :string(255)      default("")
#  number                 :string(255)
#  name                   :string(255)
#  avatar                 :string(255)
#  birthday               :string(255)
#  tec_position           :string(255)
#  email                  :string(255)
#  qualification          :string(255)
#  fax                    :string(255)
#  final_education        :string(255)
#  final_degree           :string(255)
#  tec_expertise          :string(255)
#  resume                 :text(65535)
#  tec_situation          :text(65535)
#  tec_service            :text(65535)
#  deleted_at             :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  sex                    :string(255)
#  signature              :text(65535)
#  academy_id             :integer
#

require 'csv'
class Teacher < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable#, :validatable

  acts_as_voter

  has_many :comment, as: :usertable, dependent: :destroy
  has_one :image, as: :imageable
  has_many :teacher_courses, dependent: :destroy
  has_many :courses, through: :teacher_courses
  has_many :teacher_grades, dependent: :destroy
  has_many :grades, through: :teacher_grades
  belongs_to :academy

  has_many :papers, dependent: :destroy

  # Virtual attribute for authenticating by either username or phone
  attr_accessor :login

  validates_presence_of     :phone
  validates_uniqueness_of   :phone, case_sensitive: false
  validates_uniqueness_of   :number, case_sensitive: false
  validates :password, presence: true, length: {minimum:4,maximum: 32}, on: :create
  validates_confirmation_of :password, on: :create

  #去除number中的空格
  before_create do
    self.number = self.number.split(" ").join("")
  end

  def self.find_for_database_authentication(warden_conditions)
   conditions = warden_conditions.dup

   login = conditions.delete(:login)

   where(conditions).where(["lower(number) = :value OR lower(phone) = :value", { :value => login.strip.downcase }]).first
  end

  #有你昵称显示昵称，没有则显示其名字
  def show_name
    self.name
  end

   #页面头像显示
  def show_image
    self.image.present? ? self.try(:image).try(:avatar).try(:url, :t_280_370) : "teacher-default.jpg"
  end

  #excel,csv导入功能
  def self.import(file)
    allowed_attributes = [ "number", "name", "birthday", "tec_position", "phone", "email", "final_education", "final_degree"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(2)
    (3..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      teacher = Teacher.new
      u_hash = row.to_hash.select { |k,v| allowed_attributes.include? k }
      u_hash["number"] = row["number"].to_i.to_s.split(" ").join("")
      u_hash["phone"] = row["phone"].to_i.to_s.split(" ").join("")
      teacher.password = "8888"
      teacher.password_confirmation = "8888"
      teacher.attributes = u_hash
      teacher.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "未知格式: #{file.original_filename}"
    end
  end

end

app/controllers/admin/teachers_controller.rb
module Admin
class TeachersController < ApplicationController
  load_and_authorize_resource
  before_action :set_teacher, only: [:edit, :update, :destroy]

  def index
    @teachers = Teacher.page(params[:page]).per(15)
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.image = Image.new
    @teacher.image.avatar = params[:teacher][:image]
    @teacher.teacher_grades << TeacherGrade.new(grade_id: params[:teacher][:grade_ids], teacher_id: @teacher.id)
    @teacher.password = "8888"
    @teacher.password_confirmation = "8888"
    if @teacher.save && @teacher.image.save
      flash.now[:notice] = "教师创建成功"
      return redirect_to admin_teachers_url
    else
      p @teacher.errors
      return render :new
    end
  end

  def edit
     session[:return_to] ||= request.referer
  end

  def update
    @teacher.image = Image.new if @teacher.image.blank? && params[:teacher][:image].present?
    params[:teacher][:grade_ids] ||= []
    if @teacher.update(teacher_params)
      @teacher.image.update(avatar: params[:teacher][:image]) if params[:teacher][:image].present?
      flash.now[:notice] = "教师更新成功"
      redirect_to session.delete(:return_to)
    else
      return render action: :update
    end
  end

  def show
  end

  def import
    Teacher.import(params[:file])
    redirect_to admin_teachers_url
  end

  def destroy
    @teacher.destroy
    return redirect_to admin_teachers_url
  end

  private
    def set_teacher
      @teacher = Teacher.where(id: params[:id]).first
    end
    def teacher_params
      params.require(:teacher).permit(:number, :phone, :username, :number, :name, :avatar,
                                    :birthday, :tec_position, :email, :qualification,
                                    :fax, :final_education, :final_degree, :tec_expertise,
                                    :resume, :tec_situation, :tec_service, :deleted_at,
                                    :sex, :grade_id, :signature, {grade_ids: []}, 
                                    :academy_id, :password, :password_confirmation)
    end
end
end

app/controllers/teachers/confirmations_controller.rb
class Teachers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/teachers/omniauth_callbacks_controller.rb
class Teachers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teachers/passwords_controller.rb
class Teachers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teachers/registrations_controller.rb
class Teachers::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers/sessions_controller.rb
class Teachers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    if current_user.present?
      flash[:notice] = "您已登录了学生的账号，请先退出再切换登录用户。"
      redirect_to root_path
    else
      super
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/teachers/unlocks_controller.rb
class Teachers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/teachers_helper.rb
module Admin::TeachersHelper
end

app/views/teachers/_left_bar.html.erb
<div id="left-bar">
  <div class="out-wrap">
    <div class="top-title">
      个人中心
    </div>
    <ul class="list">
      <div class="list-bg"></div>
      <li>
        <%= link_to my_courses_teachers_path do %>
          <i class="glyphicon glyphicon-film"></i>
          <span>我的课程</span>
        <%end%>
      </li>
      <li>
        <%= link_to my_grades_teachers_path do %>
          <i class="glyphicon glyphicon-tasks"></i>
          <span>我的班级</span>
        <%end%>
      </li>
      <li>
        <%= link_to my_score_teachers_path do %>
          <i class="glyphicon glyphicon-eye-open"></i>
          <span>成绩查询</span>
        <%end%>
      </li>
      <li>
        <%= link_to my_questions_teachers_path do %>
          <i class="glyphicon glyphicon-book"></i>
          <span>我的问答</span>
        <%end%>
      </li>
      <li>
        <%= link_to discuss_center_teachers_path do %>
          <i class="glyphicon glyphicon-list-alt"></i>
          <span>讨论中心</span>
        <%end%>
      </li>
      <!-- <li>
        <%= link_to my_info_teachers_path do %>
          <i class="glyphicon glyphicon-user"></i>
          <span>教师介绍</span>
        <%end%>
      </li> -->
      <li>
        <%= link_to my_account_teachers_path do %>
          <i class="glyphicon glyphicon-cog"></i>
          <span>我的账户</span>
        <%end%>
      </li>
    </ul>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    if("<%= controller.controller_path %>" == "teachers" && "<%= controller.action_name%>" == "my_courses"){
      $("#left-bar .list .list-bg").css("top", "62px");
      $("#left-bar .list li").eq(0).find("a").addClass("active");
      $("#left-bar .list li").eq(0).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "teachers" && "<%= controller.action_name%>" == "my_grades"){
      $("#left-bar .list .list-bg").css("top", "128px");
      $("#left-bar .list li").eq(1).find("a").addClass("active");
      $("#left-bar .list li").eq(1).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "teachers" && <%= ["my_score","select_grade","select_course","show_score","show_grade_score"].include? controller.action_name %>){
      $("#left-bar .list .list-bg").css("top", "194px");
      $("#left-bar .list li").eq(2).find("a").addClass("active");
      $("#left-bar .list li").eq(2).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "teachers" && ("<%= controller.action_name%>" == "my_questions" || "<%= controller.action_name%>" == "my_answers")){
      $("#left-bar .list .list-bg").css("top", "260px");
      $("#left-bar .list li").eq(3).find("a").addClass("active");
      $("#left-bar .list li").eq(3).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "teachers" && "<%= controller.action_name%>" == "discuss_center"){
      $("#left-bar .list .list-bg").css("top", "326px");
      $("#left-bar .list li").eq(4).find("a").addClass("active");
      $("#left-bar .list li").eq(4).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "teachers" && "<%= controller.action_name%>" == "my_info"){
      $("#left-bar .list .list-bg").css("top", "392px");
      $("#left-bar .list li").eq(5).find("a").addClass("active");
      $("#left-bar .list li").eq(5).siblings().find("a").removeClass("active");
    }
    else if( ("<%= controller.action_name%>" == "my_account" || "<%= controller.action_name%>" == "edit" || "<%= controller.action_name%>" == "update")){
      $("#left-bar .list .list-bg").css("top", "458px");
      $("#left-bar .list li").eq(6).find("a").addClass("active");
      $("#left-bar .list li").eq(6).siblings().find("a").removeClass("active");
    }
  });
</script>

app/views/teachers/_question.html.erb
<% questions.each do |question| %>
	<tr>
	  <td><%= question.title %></td>
	  <td><%= question.signal_score %></td>
	  <td><%= question.correct_option %></td>
	  <td><%= question.correct_hint %></td>
	</tr>
<% end %>

app/views/teachers/_teacher_info.html.erb
<div id="teacher-info" class="teacher-wrapper">
	<div class="teacher-img">
		<%= image_tag( current_teacher.show_image )%>
	</div>
	<div class="teacher-data">
	  <div class="title-content">
      <p class="title">基本信息</p>
      <p class="line"></p>
	  </div>
	  <ul>
	  	<li class="width-50">
	  		姓名:	<%= current_teacher.name %>
	  	</li>
	  	<li class="width-50">
	  		出生年月:	 <%= current_teacher.birthday %>
	  	</li>
	  	<li class="width-50">
	  		专业技术职位:	<%= current_teacher.tec_position %>
	  	</li>
	  	<li class="width-50">
	  		所属院系:	 <%= current_teacher.try(:academy).try(:name) %>
	  	</li>
	  	<li class="width-50">
	  		手机号码:	 <%= current_teacher.phone %>
	  	</li>
	  	<li class="width-50">
	  		电子邮箱:	 <%= current_teacher.email %>
	  	</li>
	  	<li class="width-50">
	  		资格证书:	 <%= current_teacher.qualification %>
	  	</li>
	  	<li class="width-50">
	  		传真号码:	 <%= current_teacher.fax %>
	  	</li>
	  	<li class="width-50">
	  		最终学历:	 <%= current_teacher.final_education %>
	  	</li>
	  	<li class="width-50">
	  		最高学位:	 <%= current_teacher.final_degree %>
	  	</li>
	  	<li class="width-100">
	  		教学与技术专长:	 C语言程序基础，ASP.NET开发， java编程基础， 数据库技术
	  	</li>
	  </ul>
	  <div class="title-content">
      <p class="title">工作简历</p>
      <p class="line"></p>
	  </div>
	  <ul>
		<% if current_teacher.resume.present? %>
		  	<% current_teacher.resume.split("\r\n").each do |resume| %>
			  	<li class="width-100">
			  		<%= resume %>
			  	</li>
		  	<% end %>
		<% else %>
			<li class="width-100">暂未填写工作简历 <%= link_to "前往填写>>", "#{my_account_teachers_path}#teacher_resume" %></li>
		<% end %>
	  </ul>
	</div>
</div>

app/views/teachers/discuss_center.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "_teacher_page" , 'data-turbolinks-track' => false%>
<%end%>

<div class="main-content">
  <%= render "left_bar" %>
  <%= render "teacher_info" %>
  <div class="teacher-content teacher-wrapper">
  	<div class="nav-bar">
  		<%= link_to  "我的评论" , "#", class: "btn btn-default by-btn-bg" %>
  	</div>
  	<div class="teacher-info-content teacher-wrapper">
  		<div class="infos">
  		 	<ul class="my-questions">
  		 		<% if @comments.blank? %>
  		 		  <div class="blank-alert">
		          <%= render partial: 'common/blank_alert', locals: {message: '您暂未发起任何讨论!'}%>
		        </div>
	        <% else %>
	        	<% @comments.each do |comment| %>
	        		<li>
	  		 		  <div class="avatar">
	  		 		  	<%= image_tag comment.try(:usertable).try(:show_image),class: "img-circle" %>
	  		 		  </div>
	  		 		  <div class="question-info">
	  		 		  	<p class="name">
		  		 		    <%= current_teacher.show_name %>
		  		 		    <span>提问</span>
		  		 		  </p>
		  		 		  <p class="content">
                  <%= link_to comment.body,show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%>
                </p>
		  		 		  <% if comment.has_children? %>
                  <p><span class="text-muted">[最新回答]</span>
                  <span><%= comment.children.last.try(:usertable).try(:show_name) %>:<span>
                  <span class="text-muted"> <%= link_to comment.children.last.try(:body),show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%></span></p>
		            <% end %>
		  		 		  <p class="time">时间: <%= comment.created_at.try(:strftime,'%Y-%m-%d %H:%M:%S') %></p>
	  		 		  </div>
	  		 		  <div class="answer-broswer">
	  		 		  	<div class="list bl <%= comment.has_children? ? "text-success" : "text-muted"%>">
	  		 		  		<p class="num"><%= comment.children.size %></p>
	  		 		  		<p class="answer">回答</p>
	  		 		  	</div>
	  		 		  	<div class="list">
	  		 		  		<p class="num">0</p>
	  		 		  		<p class="answer">浏览</p>
	  		 		  	</div>
	  		 		  </div>
	  		 		</li>
	        	<% end %>
	        <% end %>
  		 	</ul>
  		</div>
  	</div>
    <div class="paginate text-center">
        <%= paginate @comments %>
    </div>
  </div>
</div>

app/views/teachers/my_answers.html.erb
<%= content_for :script do %>
   <%= javascript_include_tag "_teacher_page" , 'data-turbolinks-track' => false%>
<%end%>

<div class="main-content">
  <%= render "left_bar" %>
  <%= render "teacher_info" %>
  <div class="teacher-content teacher-wrapper">
  	<div class="nav-bar">
  		<%= link_to  "我的提问" , my_questions_teachers_path, class: "btn btn-default" %>
  		<%= link_to  "我的回复", my_answers_teachers_path , class: "btn btn-default by-btn-bg" %>
  	</div>
  	<div class="teacher-info-content teacher-wrapper">
  		<div class="infos">
  		 	<ul class="my-questions">
  		 		<% if @answer_comments.blank? %>
  		 		  <div class="blank-alert">
		          <%= render partial: 'common/blank_alert', locals: {message: '您暂未发起任何回复!'}%>
		        </div>
	        <% else %>
	        	<% @answer_comments.each do |comment| %>
	        		<li>
  	  		 		  <div class="avatar">
  	  		 		  	<%= image_tag comment.try(:usertable).try(:show_image),class: "img-circle" %>
  	  		 		  </div>
  	  		 		  <div class="question-info">
  	  		 		  	<p class="name">
  		  		 		    <%= current_teacher.show_name %>
  		  		 		    <span>回答</span>
  		  		 		  </p>
  		  		 		  <p class="content"><%= link_to comment.body,show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%> </p>
  		  		 		  <% if comment.parent.present? %>
                    <p><span class="text-muted">[问题]</span>
                    <span><%= comment.parent.try(:usertable).try(:show_name) %>:<span>
                    <span class="text-muted">
                    <%= link_to comment.parent.body,show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%>
                    </span></p>
  		           <% end %>
  		  		 		  <p class="time">时间: <%= comment.created_at.try(:strftime,'%Y-%m-%d %H:%M:%S') %></p>
  	  		 		  </div>
  	  		 		  <div class="answer-broswer">
  	  		 		  	<div class="list bl <%= comment.parent.present? ? "text-success" : "text-muted"%>">
  	  		 		  		<p class="num"><%= comment.parent.children.size %></p>
  	  		 		  		<p class="answer">回答</p>
  	  		 		  	</div>
  	  		 		  	<div class="list">
  	  		 		  		<p class="num">0</p>
  	  		 		  		<p class="answer">浏览</p>
  	  		 		  	</div>
  	  		 		  </div>
  	  		 		</li>
	        	<% end %>
	        <% end %>
  		 	</ul>
  		</div>
  	</div>
  	<div class="paginate text-center">
        <%= paginate @answer_comments %>
    </div>
  </div>
</div>

app/views/teachers/my_courses.html.erb
<div class="main-content">
  <%= render "left_bar" %>
  <%= render "teacher_info" %>
  <div class="teacher-content teacher-wrapper">
  	<div class="nav-bar">
  		<span class="btn btn-primary by-btn-bg">课程中心</span>
      <%= link_to new_sub_course_path, remote: true, class: 'btn btn-success pull-right' do %>
        <span class="glyphicon glyphicon-plus">创建子课程</span>
      <% end %>
  	</div>
    <% if @courses.present? %>
      <ul id="subCoursesList">
        <% @courses.each_with_index do |course, index|%>
          <p><span><%= index+1 %>. </span><%= course.name %></p>
          <% course.sub_courses.each do |sub_course|%>
            <li>
              <span class="title"><%= sub_course.name %></span>
              <%= link_to "导入试题", import_question_teachers_path(sub_course_number: sub_course.number), class: "upload pull-right" %>
              <%= link_to "编辑", edit_sub_course_path(sub_course), remote: true, class: "edit pull-right" %>
              <%= link_to "删除", sub_course_path(sub_course.id), data: {confirm: '确认要删除吗'}, method: :delete, class: "delete pull-left" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <%= render partial: 'common/blank_alert', locals: {message: '您尚未创建子课程!'}%>
    <% end %>
  </div>
</div>