config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_for :teachers, controllers: {
        sessions: 'teachers/sessions'
      }
  devise_for :managers, controllers: {
      sessions: 'managers/sessions'
    }
  root :to => "home#index"

  get "select_courses", to: "home#select_courses", as: :select_courses_home
  get "courses/:number", to: "courses#show", as: :show_courses
  get "courses/:number/after_class", to: "courses#after_class", as: :after_class_courses
  resources :errors, only: :index
  #限定子课程编号为数字
  constraints(number: /\d+/) do
    get "sub_courses/:number", to: "sub_courses#show", as: :show_sub_courses
  end
  get "courses/:number/exams/new", to: "exams#new", as: :new_courses_exams

  post "sub_courses/comment_create_list"
  get "sub_courses/comment_create_list"
  post "sub_courses/reply_comment_list"
  get "sub_courses/comment_praise"
  post "sub_courses/collect_or_praise"
  
  #当子课程为pdf等格式文件时下载链接
  get "/sub_courses/:number/download", to: "sub_courses#download", as: :download_sub_course

  get "/learning_center", to: "courses#learning_center", as: :courses_learning_center
  resources :courses, only: [:index] do
  	resources :sub_courses, only: [:show]
    collection do
      post :course_collect
      post :course_praise
    end
  end

  resources :sub_courses, only: [:new, :create, :edit, :update, :destroy]

  #精品课程申报
  resources :apply_courses, only: [:index]

  #讨论中心
  resources :discusses, except: [:edit, :update, :destroy] do 
    collection do
      post :reply_topic
      get :sorts
      get :learns
      get :innovations
    end
  end

  # 测试中心
  resources :papers do
    member do
      get :questions
      patch :import
      get :students
    end

    resources :user_papers do
      collection do
        get :detail
        delete :destroy_grade
        get :export_grade
      end
    end
    resources :answers
  end

  #限定教师编号为数字形式
  constraints(number: /\d+/) do
    get "teachers/:number", to: "teachers#show", as: :show_teachers
  end

  resources :teachers, only: [:index, :update] do
    collection do
      get :my_courses
      get :my_grades
      get :my_info
      get :my_account
      get :upload_course_ware
      get :discuss_center
      get :my_questions
      get :my_answers
      get :my_score
      get :select_grade
      get :select_exam
      get :select_course
      get :show_score
      get :show_grade_score
      post :upload_attachment
      get :import_question
      post :import
      get :export
    end
    member do
      patch :update_password
      get :get_sub_course
      get :grade_students
    end
  end

  resources :exams, only: [:new, :create, :show, :index]  do 
    collection do
      get :test_new
      get :show_test
    end
  end

  resources :user, only: [:show, :update] do
    collection do
      post :get_specialties
      post :get_grades
      get :show
      get :my_courses
      get :my_exams
      get :score_search
      get :my_collect
      get :my_questions
      get :my_answers
      get :discuss_center

      post :update_password
    end
  end

  namespace :admin do
    root "home#index"
    resources :managers
    resources :specialties
    resources :questions, only: [] do
      collection do
         post :import
      end
    end
    resources :grades
    resources :courses do
      member do
        post :delete, :delete, :restore
        patch :delete, :delete, :restore
      end
      resources :sub_courses do
        member do
          patch :higher, :lower, :delete, :restore
          post :lower, :higher, :delete, :restore
        end
        resources :questions, only: [:index, :destroy]
      end
    end

    resources :teachers do
      collection do
        post :import
      end
    end

    resources :academies

    resources :categories

    resources :users do
      collection do
        post :import
      end
    end
  end

end

app/models/paper.rb
# == Schema Information
#
# Table name: papers
#
#  id          :integer          not null, primary key
#  teacher_id  :integer
#  course_id   :integer
#  name        :string(255)
#  content     :text(65535)
#  start_at    :date
#  end_at      :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  total_score :integer
#

class Paper < ActiveRecord::Base
  belongs_to :course
  has_many :user_papers, dependent: :destroy
  has_many :paper_questions, dependent: :destroy

  validates_presence_of :course_id, :name
  validates_presence_of :start_at, :end_at, message: "请输入YYYY-MM-DD格式的日期"

  # 试卷导入
  def import(file)
    spreadsheet = Paper.open_spreadsheet(file)
    header = [:question_type, :signal_score, :title, :correct_answer, :correct_hint]
    options_index = {0 => "A", 1 => "B", 2 => "C", 3 => "D", 4 => "E"}
    begin
      PaperQuestion.transaction do
        total_score = 0 
        self.paper_questions.destroy_all # 删除原来的题
        spreadsheet.each_with_index  do |row, index|
          next if index == 0
          # 题目创建
          paper_question = PaperQuestion.new 
          attrs = Hash[[header, row.slice(0..(header.size - 1))].transpose]
          attrs[:question_type] = PaperQuestion::QUESTIONTYPE.invert[attrs[:question_type]]
          paper_question.attributes = attrs
          paper_question.paper_id = self.id
          paper_question.save!

          total_score += paper_question.signal_score # 总分计算

          # 选择题时保存其选项
          if paper_question.single? || paper_question.multi?
            row.slice(header.size..row.size).each_with_index do |option, index|
              PaperOption.create!(content: option, index_type: options_index[index], paper_question_id: paper_question.id) if options_index[index].present? && option.present?
            end
          end
        end
        self.update(total_score: total_score)
      end
    rescue Exception => e
      puts "===================import======================="
      puts e.message
      puts "===================import======================="
      ActiveRecord::Rollback
    end
    
  end 


  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "未知格式: #{file.original_filename}"
    end
  end


  # 按班级导出成绩单
  def export_by_grade(grade)
    xls_report = StringIO.new
    book = Spreadsheet::Workbook.new

    sheet = book.create_worksheet :name => self.try(:paper).try(:name)

    # 考试信息
    sheet.row(0).concat ['学院', grade.specialty.academy.name]
    sheet.row(1).concat ['专业', grade.specialty.name]
    sheet.row(2).concat ['班级', grade.name]

    user_papers = UserPaper.includes(:user).where(users: {grade_id: grade.id}, user_papers: {paper_id: self.id}).order("users.number asc")

    title = ['学号', '姓名', '得分']
    sheet.row(3).concat title

    offset = 4 #学生信息起始行
    user_papers.each_with_index do |user_paper, index|
      user = user_paper.user
      content = [user.number, user.name, user_paper.total_score]
      sheet.row(offset + index).concat content
    end

    book.write xls_report
    xls_report.string
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :authenticate_user_or_teacher, only: :index
  before_action :authenticate_teacher!, except: :index

  def index
    if params[:type] == 'ing'
      @papers = (current_user || current_teacher).papers.after(Date.today, field: "end_at").before(Date.today, field: "start_at") 
    elsif params[:type] == 'end'
      @papers = (current_user || current_teacher).papers.before(Date.today - 1, field: "end_at") 
    else
      @papers = (current_user || current_teacher).papers.after(Date.today + 1, field: "start_at")  
    end
  end

  def new
    @paper = Paper.new
  end 

  def create
    @paper = Paper.new paper_params
    @paper.teacher_id = current_teacher.id
    if @paper.save
      redirect_to papers_path
    else
      render :new
    end
  end

  def edit
    @paper = Paper.where(id: params[:id]).first
  end

  def update
    @paper = Paper.where(id: params[:id]).first
    if @paper.update(paper_params)
      redirect_to papers_path
    else
      render :edit
    end
  end


  def questions
    @paper = Paper.where(id: params[:id]).first
  end

  def import
    @paper = Paper.where(id: params[:id]).first
    @paper.import(params[:attachment])
    redirect_to questions_paper_path(@paper)
  end

  def students
    @paper = Paper.where(id: params[:id]).first
    @grades = Grade.includes(users: :user_papers).where(user_papers: {paper_id: @paper.id}).distinct
  end

  def destroy
    @paper = Paper.where(id: params[:id]).first
    @paper.destroy if @paper.present?
    redirect_to papers_path
  end

  private

  def paper_params
    params.require(:paper).permit(:course_id, :name, :content, :start_at, :end_at)
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_user_paper.html.erb
<br><h4>班级参考人详情：</h4><br>
<table class="table table-bordered students-list">
  <thead>
    <tr>
      <th>No.</th>
      <th>学院</th>
      <th>专业</th>
      <th>班级</th>
      <th>学号</th>
      <th>姓名</th>
      <th>测试状态</th>
      <th>阅卷状态</th>
      <th>客观题得分</th>
      <th>得分</th>
      <th>阅卷</th>
    </tr>
  </thead>
  <tbody>
    <% user_papers.each_with_index do |user_paper, index|%>
    <tr>
      <td align="center"><%= index + 1 %></td>
      <td align="center"><%= user_paper.try(:user).try(:grade).try(:specialty).try(:academy).try(:name) %></td>
      <td align="center"><%= user_paper.try(:user).try(:grade).try(:specialty).try(:name) %></td>
      <td align="center"><%= user_paper.try(:user).try(:grade).try(:name) %></td>
      <td align="center"><%= user_paper.try(:user).try(:number) %></td>
      <td align="center"><%= user_paper.try(:user).try(:name) %></td>
      <td align="center" class="<%= 'text-danger' unless user_paper.answered %>"><%= user_paper.answered ? "已考" : "未考" %></td>
      <td align="center" class="<%= 'text-warning' unless user_paper.evaluated %>"><%= user_paper.evaluated ? "已阅卷" : "未阅卷" %></td>
      <td align="center"><%= user_paper.objective_total %></td>
      <td align="center"><%= user_paper.total_score %></td>
      <td align="center"><%= link_to_unless !user_paper.answered, "阅卷", edit_paper_user_paper_path(user_paper.paper, user_paper) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% if user_papers.present? %>
  <div class="row text-center">
    <%= link_to("导出成绩单", export_grade_paper_user_papers_path(user_papers.first.paper,grade_id: user_papers.first.user.grade.id), class: "btn btn-info btn-lg") %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<div class="main-content">
  <section class="common-title">
    <span class="pull-left">编辑测试</span>
  </section>
  
  <div class="exams-list container">
    <%= simple_form_for(@paper, url: paper_path(@paper), method: :put, wrapper: "horizontal_form28", html: { class: "form-horizontal", multipart: true }) do |f| %>
      <%= f.input :course_id, collection: current_teacher.courses %>
      <%= f.input :name %>
      <%= f.input :content %>
      <%= f.input :start_at, as: :string, placeholder: "请输入YYYY-MM-DD格式的日期" %>
      <%= f.input :end_at, as: :string, placeholder: "请输入YYYY-MM-DD格式的日期" %>
      <div class="col-sm-8 col-sm-offset-1 text-center">
        <%= f.submit "提交", class: "btn btn-success" %>
      </div><br>
    <% end %>
  </div>
</div>

app/views/papers/index.html.erb
<div class="main-content">
  <section class="common-title">
    <span class="pull-left">考试中心</span>
  </section>

  <ul id="examListMenu" class="nav nav-pills discuss-menu">
    <li class="<%= 'active' if params[:type].blank? %>"><%= link_to("即将开始", papers_path) %></li>
    <li class="<%= 'active' if params[:type] == 'ing' %>"><%= link_to("正在进行", papers_path(type: "ing")) %></li>
    <li class="<%= 'active' if params[:type] == 'end' %>"><%= link_to("已结束", papers_path(type: "end")) %></li>
    <% if teacher_signed_in? %>
      <li class="navbar-right create-discuss">
        <%= link_to new_paper_path do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新建测试
        <% end %>
      </li>
    <% end %>
  </ul>
  <br>
  <div class="exams-list">
    <table class="table table-bordered">
      <tr>
        <th>测试科目</th>
        <th>测试标题</th>
        <th>测试内容</th>
        <th>测试时间</th>
        <th>测试人数</th>
        <% if teacher_signed_in? || (user_signed_in? && params[:type].present?) %>
          <th>操作</th>
        <% end %>
      </tr>
      <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.course.name %></td>
        <td><%= paper.name %></td>
        <td><%= paper.content %></td>
        <td align="center"><%= paper.start_at.strftime("%F") %>至<%= paper.end_at.strftime("%F") %></td>
        <td align="center">
          <%= params[:type].present? ? "#{paper.user_papers.answered.size }/#{paper.user_papers.size }" : paper.user_papers.size %>
        </td>
        <% if teacher_signed_in? || (user_signed_in? && params[:type].present?) %>
        <td align="center">
          <% if teacher_signed_in? %>
            <%= link_to("编辑", edit_paper_path(paper)) %> | 
            <%= link_to("试卷", questions_paper_path(paper)) %> |
            <%= link_to("考生", students_paper_path(paper)) %> | 
            <%= link_to("删除", paper_path(paper), method: :delete, data: { confirm: "确认删除该测试？" } ) %>
          <% elsif user_signed_in? %>
            <% if params[:type] == 'ing' %>
              <%= link_to("进入测试", new_paper_answer_path(paper)) %>
            <% elsif params[:type] == 'end'%>
              <%= link_to("成绩查询", detail_paper_user_papers_path(paper)) %>
            <% end %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/papers/new.html.erb
<div class="main-content">
  <section class="common-title">
    <span class="pull-left">新建测试</span>
  </section>
  
  <div class="exams-list container">
    <%= simple_form_for(@paper, url: papers_path(@paper), wrapper: "horizontal_form28", html: { class: "form-horizontal", multipart: true }) do |f| %>
      <%= f.input :course_id, collection: current_teacher.courses %>
      <%= f.input :name %>
      <%= f.input :content %>
      <%= f.input :start_at, as: :string, placeholder: "请输入YYYY-MM-DD格式的日期" %>
      <%= f.input :end_at, as: :string, placeholder: "请输入YYYY-MM-DD格式的日期" %>
      <div class="col-sm-8 col-sm-offset-1 text-center">
        <%= f.submit "提交", class: "btn btn-success" %>
      </div><br>
    <% end %>
  </div>
</div>

app/views/papers/questions.html.erb
<div class="main-content">
  <section class="common-title">
    <span class="pull-left"><%= @paper.name %></span>
  </section>
  
  <div class="exams-list container">
    <%= simple_form_for(@paper, url: import_paper_path(@paper), wrapper: "horizontal_form28", html: { class: "form-horizontal", multipart: true }) do |f| %>
      <table class="table impport-table">
        <tr>
          <td width="50%" align="right"><%= file_field_tag :attachment %></td>
          <td ><%= f.submit "导入试卷", class: "btn btn-success", onclick: "if($('#attachment').val()==''){alert('请选择要上传的文件');return false;}" %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "导入模板下载", URI.encode('/excels/试卷导入模板.xls'), class: "btn btn-info" %></td>
        </tr>
      </table>
    <% end %>

    <div class="questions-list">
      <div class="row header text-center">
        <h2 class=""><%= @paper.name %></h2>
        <p>总分数：<%= @paper.total_score %> &nbsp;&nbsp;&nbsp;&nbsp; 总题数：<%= @paper.paper_questions.size %></p>
      </div>
      
      <% if @paper.paper_questions.single.present? %>
        <h4>单选题：</h4>
        <div class="questions">
          <% @paper.paper_questions.single.each_with_index do |question, index| %>
            <div class="paper-question">
              <div class="title"><%= index + 1 %>、<span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %>（<span class="text-danger"><%= question.correct_answer %></span>）</div>
              <div class="option">
                <% question.paper_options.each do |option| %>
                  <p><%= option.index_type + '、' + option.content %></p>
                <% end %>
                <p class="hint text-danger">
                答案解析：<%= question.correct_hint %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <% if @paper.paper_questions.multi.present? %>
        <h4>多选题：</h4>
        <div class="questions">
          <% @paper.paper_questions.multi.each_with_index do |question, index| %>
            <div class="paper-question">
              <div class="title"><%= index + 1 %>、<span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %>（<span class="text-danger"><%= question.correct_answer %></span>）</div>
              <div class="option">
                <% question.paper_options.each do |option| %>
                  <p><%= option.index_type + '、' + option.content %></p>
                <% end %>
                <p class="hint text-danger">
                答案解析：<%= question.correct_hint %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>


      <% if @paper.paper_questions.judge.present? %>
        <h4>判断题</h4>
        <div class="questions">
          <% @paper.paper_questions.judge.each_with_index do |question, index| %>
            <div class="paper-question">
              <div class="title"><%= index + 1 %>、<span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %>（<span class="text-danger"><%= question.correct_answer %></span>）</div>
              <div class="option">
                <p class="hint text-danger">
                答案解析：<%= question.correct_hint %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <% if @paper.paper_questions.fill.present? %>
        <h4>填空题：</h4>
        <div class="questions">
          <% @paper.paper_questions.fill.each_with_index do |question, index| %>
            <div class="paper-question">
              <div class="title"><%= index + 1 %>、<span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %></div>
              <div class="option">
                <p class="hint text-danger">
                  答案解析：<%= question.correct_hint %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <% if @paper.paper_questions.que_an.present? %>
        <h4>问答题：</h4>
        <div class="questions">
          <% @paper.paper_questions.que_an.each_with_index do |question, index| %>
            <div class="paper-question">
              <div class="title"><%= index + 1 %>、<span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %></div>
              <div class="option">
                <p class="hint text-danger">
                  答案解析：<%= question.correct_hint %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/papers/students.html.erb
<div class="main-content">
  <section class="common-title">
    <span class="pull-left"><%= @paper.name %></span>
  </section>
  
  <div class="exams-list container">
    <div class="row header">
      <div class="col-sm-12"><h4>以下为参加测试的班级<%= link_to "添加测试班级", new_paper_user_paper_path(@paper), remote: true, format: :js, class: "btn btn-info pull-right " %></h4></div>
    </div>
    <table class="table table-bordered table-hover students-list">
      <thead>
        <tr>
          <th>学院</th>
          <th>专业</th>
          <th>班级</th>
          <th>班级人数</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% @grades.each do |grade| %>
          <tr>
            <td><%= grade.try(:specialty).try(:academy).try(:name) %></td>
            <td><%= grade.try(:specialty).try(:name) %></td>
            <td><%= grade.name %></td>
            <td align="center"><%= grade.users.size %></td>
            <td align="center">
              <%= link_to "详情", paper_user_papers_path(@paper, grade_id: grade.id), remote: true, format: :js %> | 
              <%= link_to "删除", destroy_grade_paper_user_papers_path(@paper, grade_id: grade.id), method: :delete, data: { confirm: "确认删除该班级？" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div id="userPaperList">
    </div>
  </div>
</div>

<div id="addGrade" class="modal fade">
  <%= render "user_papers/add_grade" %>
</div>