config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_for :teachers, controllers: {
        sessions: 'teachers/sessions'
      }
  devise_for :managers, controllers: {
      sessions: 'managers/sessions'
    }
  root :to => "home#index"

  get "select_courses", to: "home#select_courses", as: :select_courses_home
  get "courses/:number", to: "courses#show", as: :show_courses
  get "courses/:number/after_class", to: "courses#after_class", as: :after_class_courses
  resources :errors, only: :index
  #限定子课程编号为数字
  constraints(number: /\d+/) do
    get "sub_courses/:number", to: "sub_courses#show", as: :show_sub_courses
  end
  get "courses/:number/exams/new", to: "exams#new", as: :new_courses_exams

  post "sub_courses/comment_create_list"
  get "sub_courses/comment_create_list"
  post "sub_courses/reply_comment_list"
  get "sub_courses/comment_praise"
  post "sub_courses/collect_or_praise"
  
  #当子课程为pdf等格式文件时下载链接
  get "/sub_courses/:number/download", to: "sub_courses#download", as: :download_sub_course

  get "/learning_center", to: "courses#learning_center", as: :courses_learning_center
  resources :courses, only: [:index] do
  	resources :sub_courses, only: [:show]
    collection do
      post :course_collect
      post :course_praise
    end
  end

  resources :sub_courses, only: [:new, :create, :edit, :update, :destroy]

  #精品课程申报
  resources :apply_courses, only: [:index]

  #讨论中心
  resources :discusses, except: [:edit, :update, :destroy] do 
    collection do
      post :reply_topic
      get :sorts
      get :learns
      get :innovations
    end
  end

  # 测试中心
  resources :papers do
    member do
      get :questions
      patch :import
      get :students
    end

    resources :user_papers do
      collection do
        get :detail
        delete :destroy_grade
        get :export_grade
      end
    end
    resources :answers
  end

  #限定教师编号为数字形式
  constraints(number: /\d+/) do
    get "teachers/:number", to: "teachers#show", as: :show_teachers
  end

  resources :teachers, only: [:index, :update] do
    collection do
      get :my_courses
      get :my_grades
      get :my_info
      get :my_account
      get :upload_course_ware
      get :discuss_center
      get :my_questions
      get :my_answers
      get :my_score
      get :select_grade
      get :select_exam
      get :select_course
      get :show_score
      get :show_grade_score
      post :upload_attachment
      get :import_question
      post :import
      get :export
    end
    member do
      patch :update_password
      get :get_sub_course
      get :grade_students
    end
  end

  resources :exams, only: [:new, :create, :show, :index]  do 
    collection do
      get :test_new
      get :show_test
    end
  end

  resources :user, only: [:show, :update] do
    collection do
      post :get_specialties
      post :get_grades
      get :show
      get :my_courses
      get :my_exams
      get :score_search
      get :my_collect
      get :my_questions
      get :my_answers
      get :discuss_center

      post :update_password
    end
  end

  namespace :admin do
    root "home#index"
    resources :managers
    resources :specialties
    resources :questions, only: [] do
      collection do
         post :import
      end
    end
    resources :grades
    resources :courses do
      member do
        post :delete, :delete, :restore
        patch :delete, :delete, :restore
      end
      resources :sub_courses do
        member do
          patch :higher, :lower, :delete, :restore
          post :lower, :higher, :delete, :restore
        end
        resources :questions, only: [:index, :destroy]
      end
    end

    resources :teachers do
      collection do
        post :import
      end
    end

    resources :academies

    resources :categories

    resources :users do
      collection do
        post :import
      end
    end
  end

end

app/controllers/admin/users_controller.rb
module Admin
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:edit, :update, :destroy]
  def index
    @users = User.all.page(params[:page]).keyword_like(params[:keyword])
  end

  def new
    @user = User.new
    @specialties = []
    @grades = []
  end

  def create
    @user = User.new(user_params)
    @user.image = Image.new
    @user.image.avatar = params[:user][:image]
    if @user.save && @user.image.save
      flash.now[:notice] = "用户创建成功"
      return redirect_to admin_users_url
    else
      return render :new
    end
  end

  def import
    User.import(params[:file])
    redirect_to admin_users_url
  end


  def edit
    #学院专业回显赋值
    @user.academy_id = @user.try(:grade).try(:specialty).try(:academy).try(:id)
    @user.specialty_id = @user.try(:grade).try(:specialty).try(:id)

    #专业、班级下拉对应值查
    @specialties = Specialty.where(academy_id: @user.academy_id).pluck(:name, :id)
    @grades = Grade.where(specialty_id: @user.specialty_id).pluck(:name, :id)
    session[:return_to] ||= request.referer
  end

  def update
    @user.image = Image.new if @user.image.blank?
    if @user.update(user_params) && @user.image.update(avatar: params[:user][:image])
      flash.now[:notice] = "用户更新成功"
      redirect_to session.delete(:return_to)
    else
      #专业、班级下拉对应值查
      @specialties = Specialty.where(academy_id: @user.academy_id).pluck(:name, :id)
      @grades = Grade.where(specialty_id: @user.specialty_id).pluck(:name, :id)
      return :update
    end
  end

  def destroy
    @user.destroy
    return redirect_to admin_users_url
  end

  private

    def set_user
      @user = User.where(id: params[:id]).first
    end

    def user_params
      params.require(:user).permit(:campus, :phone, :nickname,:name, :username, :grade_id,
        :number, :position, :gender, :signature, :password, :password_confirmation)
    end
end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user! , except: [:get_specialties, :get_grades] 
	
  #我的账户
  def show
  	@user = current_user
    @numbers = User.quantities(current_user)
  	#学院专业回显赋值
  	@user.academy_id = @user.try(:grade).try(:specialty).try(:academy).try(:id)
  	@user.specialty_id = @user.try(:grade).try(:specialty).try(:id)

    #专业、班级下拉对应值查
  	@specialties = Specialty.where(academy_id: @user.academy_id).pluck(:name, :id)
  	@grades = Grade.where(specialty_id: @user.specialty_id).pluck(:name, :id)
  end


  #个人资料更新
  def update
  	@user = User.where(id: params[:id]).first 
    @numbers = User.quantities(current_user)
  	#未查找到对应数据时处理
  	if @user.blank?
  	  flash[:error] = "当前个人资料不存在"
  	  redirect_to user_index_path
  	end

    #头像赋值
    if params[:user][:image]
      #头像处理,未上传头像显示默认图片
      @user.image = Image.new if @user.image.blank?
      @user.image.avatar = params[:user][:image] 
    end

  	if @user.update(user_params)

      #头像更新
      @user.image.save(:validate => false)  if params[:user][:image]

  	  #更新成功
  	  #重新登录更新session以及current_user等相关变量方法的值	
  	  sign_in(:user, @user)

  	  flash.now[:notice] = "个人资料更新成功"
  	  redirect_to user_index_path
  	else
  	  #更新失败
  	  @specialties = Specialty.where(academy_id: @user.academy_id).pluck(:name, :id)
  	  @grades = Grade.where(specialty_id: @user.specialty_id).pluck(:name, :id)
  	  render :show
  	end

  end


  #我的课程
  def my_courses
    @numbers = User.quantities(current_user)
    @course = Course.where(:academy_id => current_user.academy_id)
    @collect_course = current_user.find_up_voted_items vote_scope: :collect, votable_type: :Course
  end

  #我的考试
  def my_exams
    @numbers = User.quantities(current_user)
    @exams = current_user.try(:exams)
  end

  #成绩查询
  def score_search
    @numbers = User.quantities(current_user)
    @exams = current_user.try(:exams)
  end

  #我的收藏
  def my_collect
    @numbers = User.quantities(current_user)
    @collect_course = current_user.find_up_voted_items vote_scope: :collect, votable_type: :Course
  end

  #我的问答
  def my_questions
    @numbers = User.quantities(current_user)
    @question_comments = Comment.find_root_comments_by_usertable(current_user, :answer).page(params[:page])
  end

  #我的回答
  def my_answers
    @numbers = User.quantities(current_user)
    @answer_comments = Comment.find_answer_by_usertable(current_user).page(params[:page])
  end

  #讨论中心
  def discuss_center
    @numbers = User.quantities(current_user)
    @comments = Comment.find_root_comments_by_usertable(current_user, :discuss).page(params[:page])
  end

  #修改密码
  def update_password
    @numbers = User.quantities(current_user)
    @user = current_user
  end

  #根据系别的id，查找到该系下所有的专业
  #参数：academy_id,系的id
  def get_specialties
	  @specialties = Specialty.where(academy_id: params[:academy_id]).pluck(:name, :id)
	  respond_to do |format|
      	format.js { "" }
    end
  end

  #根据专业的id，查找到该专业下所有的班级
  #参数：specialty_id,专业的id
  def get_grades
	  @grades = Grade.where(specialty_id: params[:specialty_id]).pluck(:name, :id)
	  respond_to do |format|
      	format.js { "" }
    end
  end


  private

  	def user_params
  		params.require(:user).permit(:nickname, :name, :position, :academy_id, :specialty_id, :grade_id, :gender, :signature)
  	end

    def user_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def comment_params
      params.require(:comment).permit(:title, :body)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    @numbers = User.quantities(User.first)
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    if current_teacher.present?
      flash[:notice] = "您已登录了教师的账号，请先退出再切换登录用户。"
      redirect_to root_path
    else
      super
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_nav_left.html.erb
<div id="left-bar">
  <div class="out-wrap">
    <div class="top-title">
      个人中心
    </div>
    <ul class="list">
      <div class="list-bg-user"></div>
      <li>
        <%= link_to my_courses_user_index_path do %>
          <i class="glyphicon glyphicon-sound-dolby" aria-hidden="true"></i>
          <span>我的课程</span>
        <% end %>
      </li>
      <li>
        <%= link_to my_exams_user_index_path do %>
          <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
          <span>我的测试</span>
        <% end %>
      </li>
       <li>
        <%= link_to my_questions_user_index_path do %>
          <i class="glyphicon glyphicon-tag" aria-hidden="true"></i>
          <span>我的问答</span>
        <% end %>
      </li>
       <li>
        <%= link_to discuss_center_user_index_path do %>
          <i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
          <span>讨论中心</span>
        <% end %>
      </li>
      <li>
        <%= link_to user_index_path do %>
          <i class="glyphicon glyphicon-cog" aria-hidden="true"></i>
          <span>我的账户</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    if("<%= controller.controller_path %>" == "user" && "<%= controller.action_name%>" == "my_courses"){
      $("#left-bar .list .list-bg-user").css("top", "60px");
      $("#left-bar .list li").eq(0).find("a").addClass("active");
      $("#left-bar .list li").eq(0).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "user" && "<%= controller.action_name%>" == "my_exams"){
      $("#left-bar .list .list-bg-user").css("top", "126px");
      $("#left-bar .list li").eq(1).find("a").addClass("active");
      $("#left-bar .list li").eq(1).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "user" && ("<%= controller.action_name%>" == "my_questions" || "<%= controller.action_name%>" == "my_answers")){
      $("#left-bar .list .list-bg-user").css("top", "192px");
      $("#left-bar .list li").eq(2).find("a").addClass("active");
      $("#left-bar .list li").eq(2).siblings().find("a").removeClass("active");
    }
    else if("<%= controller.controller_path %>" == "user" && "<%= controller.action_name%>" == "discuss_center"){
      $("#left-bar .list .list-bg-user").css("top", "258px");
      $("#left-bar .list li").eq(3).find("a").addClass("active");
      $("#left-bar .list li").eq(3).siblings().find("a").removeClass("active");
    }
    else if(("<%= controller.controller_path %>" == "user" && "<%= controller.action_name%>" == "show") || ("<%= controller.controller_path %>" == "users" && ("<%= controller.action_name%>" == "edit" || "<%= controller.action_name%>" == "update" ))){
      $("#left-bar .list .list-bg-user").css("top", "324px");
      $("#left-bar .list li").eq(4).find("a").addClass("active");
      $("#left-bar .list li").eq(4).siblings().find("a").removeClass("active");
    }
  });
</script>

app/views/user/get_grades.js.erb
var grade_option = "<option>请选择班级</option>";
<% @grades.each do |s| %>
	grade_option = grade_option + "<option value='<%= s[1]%>'><%= s[0]%></option>"
<% end %>
$("#common_grade_id").html(grade_option);

app/views/user/my_answers.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "_user" %>
<% end %>
<div class="row user">

  <div class="col-md-2" role="complementary">
	<%= render :partial => "nav_left" %>
  </div>

  <div class="col-md-10">

    <div class="row common-info">
      <%= render :partial => "base_info", locals: {numbers: @numbers} %>
	  </div>

	  <div class="row self-main-context">

	    <ul class="nav nav-pills">
        <li role="presentation"><%= link_to "我的提问",my_questions_user_index_path %></li>
        <li role="presentation" class="active"><%= link_to "我的回答",my_answers_user_index_path %></li>
      </ul>

      <!-- ###############################我的回答##################### -->
      <div class="questions-answers-content">
        <% if @answer_comments.blank? %>
          <div class="blank">暂时没有提问</div>
        <% else %>
          <% @answer_comments.each do |comment| %>
            <div class="row questions-answers-list">
              <div class="col-sm-1">
                <%= image_tag current_user.show_image ,class: "img-rounded max60" %>
              </div>
              <div class="col-sm-9">
                <div>奋斗在路上 <span class="grey-font">回答</span></div>
                <p>
                  <%= link_to comment.body,show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%>
                </p>
                <% if comment.parent.present? %>
                    <p><span class="text-muted">[问题]</span>
                    <span><%= comment.parent.try(:usertable).try(:show_name) %>:<span>
                    <span class="text-muted">
                    <%= link_to comment.parent.body,show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%>
                    </span></p>
                 <% end %>
                <div class="grey-font">时间：<%= comment.created_at.try(:strftime,'%Y-%m-%d %H:%M:%S') %></div>
              </div>
              <div class="col-sm-2">
                 <table class="table no-border text-muted">
                  <tr align="center">
                    <td class="<%= comment.parent.present? ? "text-success" : "text-muted"%>"><%= comment.parent.children.size %></td>
                    <td class="left-border">0</td>
                  </tr>
                  <tr align="center">
                    <td class="<%= comment.parent.present? ? "text-success" : "text-muted"%>">回答</td>
                    <td class="left-border">浏览</td>
                  </tr>
                </table>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>

      <div class="paginate text-center">
        <%= paginate @answer_comments %>
      </div>
      <!-- ###############################我的回答##################### -->

    </div>
  </div>
</div>

app/views/user/my_exams.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "_user", 'data-turbolinks-track' => true %>
<% end %>
<div class="row user">

  <div class="col-md-2" role="complementary">
	<%= render :partial => "nav_left" %>
  </div>

  <div class="col-md-10">

    <div class="row common-info">
      <%= render :partial => "base_info", locals: {numbers: @numbers} %>
	  </div>

	  <div class="row self-main-context">

	    <ul class="nav nav-pills show-content">
        <li role="presentation" class="active"><%= link_to "完成的测试","javascript:void(0);" %></li>
        <li role="presentation"><%= link_to "即将开始的测试","javascript:void(0);" %></li>
      </ul>

      <!-- ###########################完成的测试########################## -->
      <div class="div-content scoure-search">

        <% if @exams.blank? %>
          <div class="blank">没有已完成的测试</div>
        <% else %>
          <% @exams.each_with_index do |exam,index| %>
            <% if index % 2 == 0 %>
              <div class="row score-list">
            <% end %>
            <div class="col-sm-6">
              <div class="panel panel-default">
                <div class="panel-body">
                  <div class="col-sm-7 ov-hidden">
                     <%= link_to image_tag(exam.try(:sub_course).try(:course).attachment.content.url(:c_350_230), width: "100%"), show_courses_path(exam.try(:sub_course).try(:course).number), class: 'img' if exam.try(:sub_course).try(:course).attachment%>
                  </div>
                  <div class="col-sm-5">
                    <h4><%= link_to exam.try(:sub_course).try(:name), show_courses_path(exam.try(:sub_course).try(:course).try(:number)) %></h4>
                    <div class="score-detail">
                      <span class="text-primary">&bull;</span>
                      时间：<%= exam.created_at.try(:strftime,'%Y-%m-%d').try(:to_s) %>
                    </div>
                    <div class="score-detail">
                      <span class="text-primary">&bull;</span>
                      总分：100分
                    </div>
                    <div class="score-detail">
                      <span class="text-primary">&bull;</span>
                      得分：<%= exam.total_score %>分
                    </div>
                    <%= link_to "查看试卷",exam_path(exam.id) ,class: "btn btn-warning"%>
                  </div>
                </div>
              </div>
            </div>

            <% if index % 2 == 1 %>
              </div>
            <% end %>

          <% end %>

          <% if @exams.size % 2 != 0 %>
              </div>
          <% end %>
          
        <% end %>
        
      </div>
      <!-- ###########################完成的测试########################## -->

      <!-- ###########################即将开始的测试########################## -->
      <div class="my-exams-container div-content" style="display: none;" >
        <div class="row my-exams">
          <div class="col-sm-3 ov-hidden">
            <%= image_tag "my-course.png" %>
          </div>
          <div class="col-sm-9">
            <div class="my-exams-desc"> 
              <h4>CSS实现网页平滑过渡效果<br>
                <small>
                  <span>测试开始时间：2015-07-01 14:00:00</span>
                  <span>测试时间：1小时30分钟</span>
                </small>
              </h4><br>
              <p>本课程为Android消息推送的进阶篇，本课程重点讲解....本课程为Android消息推送的进阶篇，本课程重点讲解....本课程为Android消息推送的进阶篇，本课程重点讲解....本课程为Android消息推送的进阶篇，本课程重点讲解....</p>
            </div>
          </div>
        </div>
      </div>
      <!-- ###########################即将开始的测试########################## -->

    </div>

  </div>

</div>

app/views/user/my_questions.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "_user" %>
<% end %>
<div class="row user">

  <div class="col-md-2" role="complementary">
	<%= render :partial => "nav_left" %>
  </div>

  <div class="col-md-10">

    <div class="row common-info">
      <%= render :partial => "base_info", locals: {numbers: @numbers} %>
	  </div>

	  <div class="row self-main-context">

	    <ul class="nav nav-pills">
        <li role="presentation" class="active"><%= link_to "我的提问",my_questions_user_index_path %></li>
        <li role="presentation"><%= link_to "我的回答",my_answers_user_index_path %></li>
      </ul>

      <!-- ###############################我的提问##################### -->
      <div class="div-content questions-answers-content">
        <% if @question_comments.blank? %>
          <div class="blank">暂时没有提问</div>
        <% else %>
          <% @question_comments.each do |comment| %>
            <div class="row questions-answers-list">
              <div class="col-sm-1">
                <%= image_tag current_user.show_image,class: "img-rounded max60" %>
              </div>
              <div class="col-sm-9">
                <div><%= current_user.show_name %> <span class="grey-font">提问</span></div>
                <p>
                  <div>
                    <%= link_to comment.body,show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%>
                  </div>
                  <% if comment.has_children? %>
                    <span class="text-muted">[最新回答]</span>
                    <span><%= comment.children.last.try(:usertable).try(:show_name) %>:<span>
                    <span class="text-muted">
                      <%= link_to comment.children.last.try(:body),show_sub_courses_path(comment.try(:commentable).try(:number),course_number: comment.try(:commentable).try(:course).try(:number))%>
                    </span>
                  <% end %>
                </p><br>
                <div class="grey-font">时间：<%= comment.created_at.try(:strftime,'%Y-%m-%d %H:%M:%S') %></div>
              </div>
              <div class="col-sm-2">
                <table class="table no-border text-muted">
                  <tr align="center">
                    <td class="<%= comment.has_children? ? "text-success" : "text-muted"%>"><%= comment.children.size %></td>
                    <td class="left-border">0</td>
                  </tr>
                  <tr align="center">
                    <td class="<%= comment.has_children? ? "text-success" : "text-muted"%>">回答</td>
                    <td class="left-border">浏览</td>
                  </tr>
                </table>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="paginate text-center">
          <%= paginate @question_comments %>
        </div>
	    </div>
      <!-- ###############################我的提问##################### -->

    </div>
  </div>
</div>

app/views/user/show.html.erb
<div class="row user">

  <div class="col-md-2" role="complementary">
	<%= render :partial => "nav_left" %>
  </div>

  <div class="col-md-10">
    <div class="row common-info">
      <%= render :partial => "base_info", locals: {numbers: @numbers} %>
	  </div>

	  <div class="row self-main-context">
  	  <ul class="nav nav-pills show-content">
  		  <li role="presentation" class="active">
            <%= link_to("个人资料", user_index_path) %>
          </li>
          <li role="presentation" >
            <%= link_to("修改密码", edit_user_registration_path)  %>
          </li>
  	  </ul>

  	  <div class="container div-form div-content">
    		<%= simple_form_for(@user, url: user_path(current_user.id), wrapper: "horizontal_form", html: { method: :put, multipart: true, class: "form-horizontal" }) do |f| %>
          <%= f.input :number, readonly: true %>
          <%= f.input :phone, required: false, readonly: true %>
          <%= f.input :name %>
    		  <%= f.input :nickname %>
    		  <%= f.input :image , as: :file, wrapper: "horizontal_file_input"%>
    		  <%= f.input :position %>
    		  <%= render :partial => "common/common_select", locals: {f: f} %>
    		  <%= f.input :gender, collection: User::PartnerGender.to_a.reverse_each{|x| x.reverse!}, as: :radio_buttons, wrapper: "horizontal_radio_and_checkboxes", item_wrapper_class: "radio-inline" %>
    		  <%= f.input :signature, as: :text %>

    		  <div class="col-sm-5 col-sm-offset-2">
    			<p class="text-center">
    			  <%= f.submit "确认修改", class: "btn btn-success" %>
    			</p>
    		  </div>
    		<% end %>
    	  </div>

  	</div>

  </div>

</div>

<%= content_for :script do %>
  <%= javascript_tag do %>
    get_specialties_path = "<%= get_specialties_user_index_path %>"
    get_grades_path = "<%= get_grades_user_index_path %>"
  <% end %>
  <%= javascript_include_tag "_user_show", 'data-turbolinks-track' => true %>
<% end %>