config/routes.rb
Rails.application.routes.draw do
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_for :teachers, controllers: {
        sessions: 'teachers/sessions'
      }
  devise_for :managers, controllers: {
      sessions: 'managers/sessions'
    }
  root :to => "home#index"

  get "select_courses", to: "home#select_courses", as: :select_courses_home
  get "courses/:number", to: "courses#show", as: :show_courses
  get "courses/:number/after_class", to: "courses#after_class", as: :after_class_courses
  resources :errors, only: :index
  #限定子课程编号为数字
  constraints(number: /\d+/) do
    get "sub_courses/:number", to: "sub_courses#show", as: :show_sub_courses
  end
  get "courses/:number/exams/new", to: "exams#new", as: :new_courses_exams

  post "sub_courses/comment_create_list"
  get "sub_courses/comment_create_list"
  post "sub_courses/reply_comment_list"
  get "sub_courses/comment_praise"
  post "sub_courses/collect_or_praise"
  
  #当子课程为pdf等格式文件时下载链接
  get "/sub_courses/:number/download", to: "sub_courses#download", as: :download_sub_course

  get "/learning_center", to: "courses#learning_center", as: :courses_learning_center
  resources :courses, only: [:index] do
  	resources :sub_courses, only: [:show]
    collection do
      post :course_collect
      post :course_praise
    end
  end

  resources :sub_courses, only: [:new, :create, :edit, :update, :destroy]

  #精品课程申报
  resources :apply_courses, only: [:index]

  #讨论中心
  resources :discusses, except: [:edit, :update, :destroy] do 
    collection do
      post :reply_topic
      get :sorts
      get :learns
      get :innovations
    end
  end

  # 测试中心
  resources :papers do
    member do
      get :questions
      patch :import
      get :students
    end

    resources :user_papers do
      collection do
        get :detail
        delete :destroy_grade
        get :export_grade
      end
    end
    resources :answers
  end

  #限定教师编号为数字形式
  constraints(number: /\d+/) do
    get "teachers/:number", to: "teachers#show", as: :show_teachers
  end

  resources :teachers, only: [:index, :update] do
    collection do
      get :my_courses
      get :my_grades
      get :my_info
      get :my_account
      get :upload_course_ware
      get :discuss_center
      get :my_questions
      get :my_answers
      get :my_score
      get :select_grade
      get :select_exam
      get :select_course
      get :show_score
      get :show_grade_score
      post :upload_attachment
      get :import_question
      post :import
      get :export
    end
    member do
      patch :update_password
      get :get_sub_course
      get :grade_students
    end
  end

  resources :exams, only: [:new, :create, :show, :index]  do 
    collection do
      get :test_new
      get :show_test
    end
  end

  resources :user, only: [:show, :update] do
    collection do
      post :get_specialties
      post :get_grades
      get :show
      get :my_courses
      get :my_exams
      get :score_search
      get :my_collect
      get :my_questions
      get :my_answers
      get :discuss_center

      post :update_password
    end
  end

  namespace :admin do
    root "home#index"
    resources :managers
    resources :specialties
    resources :questions, only: [] do
      collection do
         post :import
      end
    end
    resources :grades
    resources :courses do
      member do
        post :delete, :delete, :restore
        patch :delete, :delete, :restore
      end
      resources :sub_courses do
        member do
          patch :higher, :lower, :delete, :restore
          post :lower, :higher, :delete, :restore
        end
        resources :questions, only: [:index, :destroy]
      end
    end

    resources :teachers do
      collection do
        post :import
      end
    end

    resources :academies

    resources :categories

    resources :users do
      collection do
        post :import
      end
    end
  end

end

app/models/user_paper.rb
# == Schema Information
#
# Table name: user_papers
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  paper_id        :integer
#  answered        :boolean          default(FALSE)
#  total_score     :integer          default(0)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  evaluated       :boolean          default(FALSE)
#  objective_total :integer          default(0)
#

class UserPaper < ActiveRecord::Base
  scope :answered, -> {where(answered: true)}

  belongs_to :user
  belongs_to :paper
  has_many :answers, dependent: :destroy

  # 根据页面传入的答题params来更新exam对象
  # 创建Exam对象的过程中，也会创建对应的ExamItem对象
  # 输入参数，key为question.id，value为option_value
  def generate_by_answer_params answer_params

    objective_total = 0

    answer_params.each do |question_id, answer_content|
      question = PaperQuestion.where(id: question_id).first
      answer = self.answers.build content: answer_content, paper_question_id: question_id, score: 0
      if question.single?
        # 单选题处理
        if answer_content.try(:strip) == question.correct_answer.try(:strip)
          answer.correct = true
          answer.score = question.signal_score
          objective_total += question.signal_score
        else
          answer.correct = false
        end
      elsif question.multi?
        # 多选题处理
        answer.content = answer_content.join('')
        if question.correct_answer.include?(answer.content)
          # 全对满分，半对一半分
          multi_score = question.correct_answer.try(:strip).size == answer.content.try(:strip).size ? question.signal_score : question.signal_score/2
          answer.score = multi_score
          objective_total += multi_score
        end
      elsif question.judge?
        # 判断题处理
        if answer_content.try(:strip) == question.correct_answer.try(:strip)
          answer.correct = true
          answer.score = question.signal_score
          objective_total += question.signal_score
        else
          answer.correct = false
        end
      end 
      answer.save 
    end

    self.answered = true
    self.objective_total = objective_total
    self.save
  end

  # 根据页面传入的答题params来更新学生考试的分数
  # 创建Exam对象的过程中，也会创建对应的ExamItem对象
  # 输入参数，key为question.id，value为option_value
  def generate_by_answer_score(answer_score)
    self.total_score = objective_total
    answer_score.each do |answer_id, score|
      answer = Answer.where(id: answer_id).first
      if answer.present?
        answer.score = (score || 0).to_i
        answer.save
        self.total_score += (score || 0).to_i
      end
    end
    self.evaluated = true
    self.save
  end

end

app/controllers/user_papers_controller.rb
class UserPapersController < ApplicationController
  before_action :authenticate_teacher!, except: :detail
  before_action :authenticate_user!, only: :detail

  def index
    @paper = Paper.where(id: params[:paper_id]).first
    @user_papers = UserPaper.includes(:user).where(users: {grade_id: params[:grade_id]}, user_papers: {paper_id: params[:paper_id]})
    respond_to do |format|
      format.js
    end
  end

  def new
    @paper = Paper.where(id: params[:paper_id]).first
    respond_to do |format|
      format.js
    end
  end 


  def create
    @paper = Paper.where(id: params[:paper_id]).first
    grade = Grade.where(id: params[:grade_id]).first
    grade.users.each do |user|
      UserPaper.create(user_id: user.id, paper_id: @paper.id)
    end
    redirect_to students_paper_path(@paper)
  end

  def detail
    @paper = Paper.includes(:paper_questions).where(id: params[:paper_id]).first
    @user_paper = UserPaper.where(user_id: current_user.id, paper_id: params[:paper_id]).first
  end

  def edit
    @paper = Paper.includes(:paper_questions).where(id: params[:paper_id]).first
    @user_paper = UserPaper.where(id: params[:id]).first
  end

  def update
    @paper = Paper.includes(:paper_questions).where(id: params[:paper_id]).first
    @user_paper = UserPaper.where(id: params[:id]).first
    @user_paper.generate_by_answer_score(params[:scores])
    redirect_to students_paper_path(@paper)
  end


  def destroy_grade
    @paper = Paper.where(id: params[:paper_id]).first
    UserPaper.includes(:user).where(users: {grade_id: params[:grade_id]}, user_papers: {paper_id: params[:paper_id]}).destroy_all
    redirect_to students_paper_path(@paper)
  end

  # 按班级导出成绩
  def export_grade
    @paper = Paper.where(id: params[:paper_id]).first
    grade = Grade.where(id: params[:grade_id]).first
    filename = URI.encode("#{@paper.name}_#{grade.try(:specialty).try(:name)}_#{grade.name}.xls")
    send_data( 
            @paper.export_by_grade(grade),
            type: "text/excel;charset=utf-8; header=present",
            filename: filename
          )
  end
end

app/helpers/user_papers_helper.rb
module UserPapersHelper
end

app/views/user_papers/_add_grade.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">添加测试班级</h4>
    </div>
    <div class="modal-body">
      <%= form_tag paper_user_papers_path(@paper), class: "form-horizontal" do |f| %>
        <div class="form-group">
          <label class="col-sm-2 control-label">学院</label>
          <div class="col-sm-9">
            <%#= f.text_field :title, class: "form-control" %>
            <%= select_tag('academy_id', options_for_select(Academy.all.pluck(:name,:id), params[:academy_id]), class: "form-control", id: "common_academy_id", prompt: "请选择学院") %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label">专业</label>
          <div class="col-sm-9">
            <%= select_tag('specialy_id', options_for_select([]), id: "common_specialty_id", class: "form-control", prompt: "请选择专业") %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label">班级</label>
          <div class="col-sm-9">
            <%= select_tag('grade_id', options_for_select([]), id: "common_grade_id", class: "form-control", prompt: "请选择班级") %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-7 col-sm-offset-2 text-center">
            <%= submit_tag "添加", class: "btn btn-info", onclick: "submit_grade();" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= content_for :script do %>
  <%= javascript_tag do %>
    get_specialties_path = "<%= get_specialties_user_index_path %>"
    get_grades_path = "<%= get_grades_user_index_path %>"
  <% end %>
  <%= javascript_include_tag "_user_show", 'data-turbolinks-track' => true %>

<% end %>

<script type="text/javascript">
  function submit_grade(){
    if($("#common_academy_id").val() == ""){
      alert("学院必须选择");
      return false;
    }
    if($("#common_specialty_id").val() == "" || $("#common_specialty_id").val() == "请选择专业"){
      alert("专业必须选择");
      return false;
    }
    if($("#common_grade_id").val() == "" || $("#common_grade_id").val() == "请选择班级"){
      alert("班级必须选择");
      return false;
    }
  }
</script>

app/views/user_papers/detail.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "jquery.countdown.min", "_exam_new", 'data-turbolinks-track' => true %>
<%end%>


<div class="main-content">
  <div class="main-title">
    <%= @paper.name %>
  </div>
  <br><br><br>
  <div class="row text-center">
    总分：<%= @paper.total_score %>  &nbsp;&nbsp;&nbsp;&nbsp;得分：<%= @user_paper.evaluated ? @user_paper.total_score : "未阅卷" %>
  </div>
  <div class="question-content">
    <%= form_tag paper_answers_path(@paper, :answer) do%>
      <% if @paper.paper_questions.single.present? %>
        <h3 class="type-title">单选题</h3>
        <% @paper.paper_questions.single.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %>&nbsp;&nbsp;<span class="text-danger">正确答案：<%= "（" + question.correct_answer  + "）"%></span></p>
          <% question.paper_options.each_with_index do |option, option_index|%>
            <p class="option">
              <%= radio_button_tag("options[#{question.id}]", option.index_type, option.index_type == question.answer.try(:content) ,disabled: true)%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_<%= select_item(option_index) %>" ><%= option.index_type + "、" + option.content %></label>
            </p>
          <% end %>
           <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.multi.present? %>
        <h3 class="type-title">多选题</h3>
        <% @paper.paper_questions.multi.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%>&nbsp;&nbsp;<span class="text-danger">正确答案：<%= "（" + question.correct_answer  + "）"%></span></p>
          <% question.paper_options.each_with_index do |option, option_index|%>
            <p class="option">
              <%= check_box_tag("options[#{question.id}][]", option.index_type, question.answer.try(:content).try(:include?,option.index_type), disabled: true, id: "options_#{question.id}_#{select_item(option_index)}")%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_<%= select_item(option_index) %>" ><%= option.index_type + "、" + option.content %></label>
            </p>
          <% end %>
           <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.judge.present? %>
        <h3 class="type-title">判断题</h3>
        <% @paper.paper_questions.judge.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%>&nbsp;&nbsp;<span class="text-danger">正确答案：<%= "（" + question.correct_answer  + "）"%></span></p>
            <p class="option">
              <%= radio_button_tag("options[#{question.id}]", "T", "T" == question.answer.try(:content), disabled: true)%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_T" >正确</label>
            </p>
            <p class="option">
              <%= radio_button_tag("options[#{question.id}]", "F", "F" == question.answer.try(:content), disabled: true)%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_F" >错误</label>
            </p>
             <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.fill.present? %>
        <h3 class="type-title">填空题</h3>
        <% @paper.paper_questions.fill.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%></p>
            <p class="option">
              回答：<%= question.answer.try(:content) %>
            </p>
            <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.que_an.present? %>
        <h3 class="type-title">问答题</h3>
        <% @paper.paper_questions.que_an.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%></p>
            <p class="option">
              回答：<%= question.answer.try(:content) %>
            </p>
             <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/user_papers/edit.html.erb
<%= content_for :script do %>
  <%= javascript_include_tag "jquery.countdown.min", "_exam_new", 'data-turbolinks-track' => true %>
<%end%>


<div class="main-content">
  <div class="main-title">
    <%= @paper.name %>
  </div>
  <br><br><br>
  <div class="row text-center">
    总分：<%= @paper.total_score %>  &nbsp;&nbsp;&nbsp;&nbsp;得分：<%= @user_paper.evaluated ? @user_paper.total_score : "未阅卷" %>
  </div>
  <div class="question-content">
    <%= form_tag paper_user_paper_path(@paper, @user_paper), method: :patch do%>
      <% if @paper.paper_questions.single.present? %>
        <h3 class="type-title">单选题</h3>
        <% @paper.paper_questions.single.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title %>&nbsp;&nbsp;<span class="text-danger">正确答案：<%= "（" + question.correct_answer  + "）"%></span></p>
          <% question.paper_options.each_with_index do |option, option_index|%>
            <p class="option">
              <%= radio_button_tag("options[#{question.id}]", option.index_type, option.index_type == question.answer.try(:content) ,disabled: true)%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_<%= select_item(option_index) %>" ><%= option.index_type + "、" + option.content %></label>
            </p>
          <% end %>
           <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.multi.present? %>
        <h3 class="type-title">多选题</h3>
        <% @paper.paper_questions.multi.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%>&nbsp;&nbsp;<span class="text-danger">正确答案：<%= "（" + question.correct_answer  + "）"%></span></p>
          <% question.paper_options.each_with_index do |option, option_index|%>
            <p class="option">
              <%= check_box_tag("options[#{question.id}][]", option.index_type, question.answer.try(:content).try(:include?,option.index_type), disabled: true, id: "options_#{question.id}_#{select_item(option_index)}")%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_<%= select_item(option_index) %>" ><%= option.index_type + "、" + option.content %></label>
            </p>
          <% end %>
           <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.judge.present? %>
        <h3 class="type-title">判断题</h3>
        <% @paper.paper_questions.judge.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%>&nbsp;&nbsp;<span class="text-danger">正确答案：<%= "（" + question.correct_answer  + "）"%></span></p>
            <p class="option">
              <%= radio_button_tag("options[#{question.id}]", "T", "T" == question.answer.try(:content), disabled: true)%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_T" >正确</label>
            </p>
            <p class="option">
              <%= radio_button_tag("options[#{question.id}]", "F", "F" == question.answer.try(:content), disabled: true)%>&nbsp;&nbsp;
              <label for="options_<%= question.id %>_F" >错误</label>
            </p>
             <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.fill.present? %>
        <h3 class="type-title">填空题</h3>
        <% @paper.paper_questions.fill.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%></p>
            <p class="option">
              回答：<%= question.answer.try(:content) %>
            </p>
            <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
            <p class="option">
              分数：<%= text_field_tag "scores[#{question.answer.try(:id)}]", question.answer.try(:score) %>
            </p>
        <% end %>
      <% end %>
      <br>
      <% if @paper.paper_questions.que_an.present? %>
        <h3 class="type-title">问答题</h3>
        <% @paper.paper_questions.que_an.each_with_index do |question, index|%>
          <p class="title"><%= index + 1 %>. <span class="text-danger"><%= "（" + question.signal_score.to_s  + "分）"%></span><%= question.title%></p>
            <p class="option">
              回答：<%= question.answer.try(:content) %>
            </p>
             <p class="option text-danger">
              答案解析：<%= question.correct_hint %>
            </p>
            <p class="option">
              分数：<%= text_field_tag "scores[#{question.answer.try(:id)}]", question.answer.try(:score) %>
            </p>
        <% end %>
      <% end %>
      <div class="form-group">
        <button type="submit" class="btn center-block btn-lg btn-primary">
          提 交 分 数
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/user_papers/index.js.erb
$("#userPaperList").html('<%= escape_javascript( render partial: "papers/user_paper", locals: {user_papers: @user_papers}) %>');

app/views/user_papers/new.html.erb
<div class="main-content">
  <section class="common-title">
    <span class="pull-left"><%= @paper.name %> | 添加考试班级</span>
  </section>
  
  <div class="exams-list container">
    <div class="header text-center">
      <%= form_tag new_paper_user_paper_path(@paper), {id: 'searchFromList', class: "form-inline"} do %>
        <div class="form-group">
          <label for="academy_id">学院：</label>
          <%= select_tag('academy_id', options_for_select(Academy.all.pluck(:name,:id), params[:academy_id]), class: "form-control", id: "common_academy_id", prompt: "请选择学院") %>
        </div>
        <div class="form-group">
          <label for="specialy_id">专业：</label>
          <%= select_tag('specialy_id', options_for_select(@specialties, params[:academy_id]), id: "common_specialty_id", class: "form-control", prompt: "请选择专业") %>
        </div>
        <div class="form-group">
          <label for="grade">班级：</label>
          <%= text_field_tag :grade, params[:grade], class: "form-control" %>
        </div>
        <button type="submit" class="btn btn-info">搜素</button>
      <% end %>
    </div>

    <table class="table table-bordered table-hover students-list">
      <thead>
        <tr>
          <th><input type="checkbox" value="all"></th>
          <th>学院</th>
          <th>专业</th>
          <th>班级</th>
          <th>班级总人数</th>
        </tr>
      </thead>
      <tbody>
        <% @grades.each do |grade| %>
          <tr>
            <td align="center"><input type="checkbox" value="<%= grade.id %>"></td>
            <td><%= grade.try(:specialty).try(:academy).try(:name) %></td>
            <td><%= grade.try(:specialty).try(:name) %></td>
            <td><%= grade.name %></td>
            <td align="center"><%= grade.users.size %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

<%= content_for :script do %>
  <%= javascript_tag do %>
    get_specialties_path = "<%= get_specialties_user_index_path %>"
    get_grades_path = "<%= get_grades_user_index_path %>"
  <% end %>
  <%= javascript_include_tag "_user_show", 'data-turbolinks-track' => true %>
<% end %>

app/views/user_papers/new.js.erb
$("#addGrade").modal();